version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      APP_HOST: ${APP_HOST}
      APP_PORT: ${APP_PORT}
      APP_WORKERS: ${APP_WORKERS}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
      - redis

  db:
    image: 'postgres:17'
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: redis-cache
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  postgres_data:
